version: "3"
name: mosquittotest
services:
    eclipse-mosquitto:
        stdin_open: true
        tty: true
        restart: always
        # network_mode: host
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            # - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - ./mosquitto/config:/mosquitto/config/
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        image: eclipse-mosquitto